/**
 * Metadata and reporting generators (license, changelog, metadata, generation reports, etc.)
 */

import type { GeneratedApp, EnhancedDownloadOptions } from './types';

/**
 * Generate MIT License
 */
export function generateMITLicense(app: GeneratedApp): string {
  const year = new Date().getFullYear();
  return `MIT License

Copyright (c) ${year} ${app.name}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;
}

/**
 * Generate CHANGELOG.md
 */
export function generateChangelog(app: GeneratedApp): string {
  return `# Changelog

All notable changes to ${app.name} will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [1.0.0] - ${new Date().toISOString().split('T')[0]}

### Added
${app.features.map((feature) => `- ${feature}`).join('\n')}

### Changed
- Initial release generated by FlashFusion

### Security
- JWT-based authentication implemented
- Input validation and sanitization
- CORS configuration
`;
}

/**
 * Generate FlashFusion metadata JSON
 */
export function generateFlashFusionMetadata(
  app: GeneratedApp,
  options: EnhancedDownloadOptions
): string {
  return JSON.stringify(
    {
      generator: {
        name: 'FlashFusion',
        version: '2.0.0',
        url: 'https://flashfusion.dev',
      },
      project: {
        name: app.name,
        description: app.description,
        version: '1.0.0',
        generatedAt: new Date().toISOString(),
        stack: app.stack,
        features: app.features,
        endpoints: app.endpoints,
      },
      options: {
        format: options.format,
        includeDocumentation: options.generateDocumentation,
        includeTests: options.generateTests,
        customBranding: options.customBranding,
      },
      stats: {
        totalFiles: app.files.length,
        codeFiles: app.files.filter((f) => f.type === 'frontend' || f.type === 'backend').length,
        configFiles: app.files.filter((f) => f.type === 'config').length,
        databaseFiles: app.files.filter((f) => f.type === 'database').length,
      },
    },
    null,
    2
  );
}

/**
 * Generate HTML generation report
 */
export function generateGenerationReport(
  app: GeneratedApp,
  _options: EnhancedDownloadOptions
): string {
  const timestamp = new Date().toLocaleString();
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generation Report - ${app.name}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; line-height: 1.6; }
    .header { background: #f8f9fa; padding: 2rem; border-radius: 8px; margin-bottom: 2rem; }
    .section { margin-bottom: 2rem; }
    .feature-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }
    .feature-item { background: #e3f2fd; padding: 1rem; border-radius: 4px; }
    .tech-stack { display: flex; flex-wrap: wrap; gap: 0.5rem; }
    .tech-badge { background: #2196f3; color: white; padding: 0.25rem 0.5rem; border-radius: 4px; font-size: 0.875rem; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
    .stat-card { background: #f5f5f5; padding: 1rem; border-radius: 4px; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${app.name}</h1>
    <p>${app.description}</p>
    <p><strong>Generated:</strong> ${timestamp}</p>
    <p><strong>Powered by:</strong> <a href="https://flashfusion.dev">FlashFusion</a></p>
  </div>

  <div class="section">
    <h2>Technology Stack</h2>
    <div class="tech-stack">
      <span class="tech-badge">Frontend: ${app.stack.frontend}</span>
      <span class="tech-badge">Backend: ${app.stack.backend}</span>
      <span class="tech-badge">Database: ${app.stack.database}</span>
      <span class="tech-badge">Auth: ${app.stack.auth}</span>
      <span class="tech-badge">Deploy: ${app.stack.deployment}</span>
    </div>
  </div>

  <div class="section">
    <h2>Features Included</h2>
    <div class="feature-list">
      ${app.features.map((feature) => `<div class="feature-item">✅ ${feature}</div>`).join('')}
    </div>
  </div>

  <div class="section">
    <h2>Project Statistics</h2>
    <div class="stats">
      <div class="stat-card">
        <h3>${app.files.length}</h3>
        <p>Total Files</p>
      </div>
      <div class="stat-card">
        <h3>${app.endpoints.length}</h3>
        <p>API Endpoints</p>
      </div>
      <div class="stat-card">
        <h3>${app.features.length}</h3>
        <p>Features</p>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Next Steps</h2>
    <ol>
      <li>Extract the project files</li>
      <li>Install dependencies: <code>npm run setup</code></li>
      <li>Configure environment variables</li>
      <li>Start development: <code>npm run dev</code></li>
      <li>Begin customization</li>
    </ol>
  </div>

  <footer style="margin-top: 4rem; padding-top: 2rem; border-top: 1px solid #ddd; text-align: center; color: #666;">
    <p>Generated by FlashFusion - The AI-powered full-stack development platform</p>
    <p><a href="https://flashfusion.dev">Visit FlashFusion</a></p>
  </footer>
</body>
</html>`;
}
